package shadow

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/rishabhju65/schemaver/internal/render"
	"github.com/rishabhju65/schemaver/internal/schema"
)

func testPool(t *testing.T) (*Pool, context.Context) {
	t.Helper()
	dsn := os.Getenv("SCHEMAVER_TEST_DATABASE_URL")
	if dsn == "" {
		t.Skip("set SCHEMAVER_TEST_DATABASE_URL to run shadow tests (needs CREATEDB)")
	}
	p, err := NewPool(dsn)
	if err != nil {
		t.Fatalf("NewPool: %v", err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	t.Cleanup(cancel)
	return p, ctx
}

// richSchema exercises the constructs most likely to survive introspection but
// break rendering: identity columns, generated columns, enums, partial and
// covering indexes, composite keys, deferred constraints and comments.
const richSchema = `
CREATE TYPE order_status AS ENUM ('pending', 'paid', 'shipped', 'cancelled');

CREATE TABLE customers (
    id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email      text NOT NULL,
    email_lc   text GENERATED ALWAYS AS (lower(email)) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT customers_email_key UNIQUE (email)
);
COMMENT ON TABLE customers IS 'People who buy things';
COMMENT ON COLUMN customers.email IS 'Login identity';

CREATE TABLE orders (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL,
    status      order_status NOT NULL DEFAULT 'pending',
    total       numeric(12,2) NOT NULL DEFAULT 0,
    placed_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT orders_total_positive CHECK (total >= 0),
    CONSTRAINT orders_customer_fk FOREIGN KEY (customer_id)
        REFERENCES customers (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX orders_customer_placed_idx ON orders (customer_id, placed_at DESC);
CREATE INDEX orders_open_idx ON orders (placed_at) WHERE status <> 'shipped';
CREATE UNIQUE INDEX orders_ref_idx ON orders (customer_id, id) INCLUDE (total);

CREATE SEQUENCE invoice_number START WITH 1000 INCREMENT BY 10;
`

// TestRenderRoundTrip is the test this package exists to make possible.
//
// It applies DDL, introspects it, renders the model back to DDL, applies that to
// a second database, and requires both to fingerprint identically. A failure
// means the renderer and the introspector disagree — and since every other
// feature is built on one or the other, that disagreement would surface
// everywhere as a phantom diff.
func TestRenderRoundTrip(t *testing.T) {
	p, ctx := testPool(t)

	original, first, err := p.Load(ctx, richSchema)
	if err != nil {
		t.Fatalf("load original schema: %v", err)
	}

	regenerated := render.Schema(original)
	t.Logf("rendered %d bytes of DDL", len(regenerated))

	_, second, err := p.Load(ctx, regenerated)
	if err != nil {
		t.Fatalf("rendered DDL did not apply:\n%v\n\n--- DDL ---\n%s", err, regenerated)
	}

	if first != second {
		t.Errorf("round trip changed the schema:\n  original    %s\n  regenerated %s\n\n--- DDL ---\n%s",
			first, second, regenerated)
	}
}

// TestLoadCapturesStructure checks Load produces a usable model, not merely a
// stable hash of something wrong.
func TestLoadCapturesStructure(t *testing.T) {
	p, ctx := testPool(t)

	s, version, err := p.Load(ctx, richSchema)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if version == "" {
		t.Fatal("Load returned an empty fingerprint")
	}

	var public *schema.Namespace
	for i := range s.Namespaces {
		if s.Namespaces[i].Name == "public" {
			public = &s.Namespaces[i]
		}
	}
	if public == nil {
		t.Fatal("public namespace missing")
	}
	if len(public.Tables) != 2 {
		t.Errorf("got %d tables, want 2", len(public.Tables))
	}
	if len(public.Enums) != 1 || public.Enums[0].Name != "order_status" {
		t.Errorf("enum not captured: %+v", public.Enums)
	}
	if len(public.Enums) == 1 && len(public.Enums[0].Labels) != 4 {
		t.Errorf("got %d enum labels, want 4", len(public.Enums[0].Labels))
	}
}

// TestLoadReportsBadDDL checks a schema error surfaces the engine's own message
// rather than a reinterpretation of it.
func TestLoadReportsBadDDL(t *testing.T) {
	p, ctx := testPool(t)

	_, _, err := p.Load(ctx, `CREATE TABLE broken (id bigint REFERENCES nonexistent (id));`)
	if err == nil {
		t.Fatal("invalid DDL was accepted")
	}
	if !strings.Contains(err.Error(), "nonexistent") {
		t.Errorf("error does not name the problem: %v", err)
	}
}

// TestVerifyProvesOutcome covers D-009 in both directions: a migration that
// produces the declared schema passes, and one that does not is blocked.
func TestVerifyProvesOutcome(t *testing.T) {
	p, ctx := testPool(t)

	const base = `CREATE TABLE widgets (id bigint PRIMARY KEY, name text NOT NULL);`
	const migration = `ALTER TABLE widgets ADD COLUMN sku text;`

	// The declared target: what the schema is supposed to look like afterwards.
	_, want, err := p.Load(ctx, base+migration)
	if err != nil {
		t.Fatalf("load target: %v", err)
	}

	got, err := p.Verify(ctx, base, migration, want)
	if err != nil {
		t.Fatalf("correct migration was rejected: %v", err)
	}
	if got != want {
		t.Errorf("got %s, want %s", got, want)
	}

	// A migration doing something other than what it declares must be blocked.
	_, err = p.Verify(ctx, base, `ALTER TABLE widgets ADD COLUMN wrong_column text;`, want)
	if err == nil {
		t.Fatal("a migration producing the wrong schema was accepted")
	}
	var mismatch *MismatchError
	if !asMismatch(err, &mismatch) {
		t.Fatalf("want MismatchError, got %T: %v", err, err)
	}
	if mismatch.Want != want {
		t.Errorf("mismatch reports want %s, expected %s", mismatch.Want, want)
	}
}

func asMismatch(err error, target **MismatchError) bool {
	m, ok := err.(*MismatchError)
	if ok {
		*target = m
	}
	return ok
}

// TestSweepRemovesAbandoned covers the crash path: a database created but never
// closed must not survive indefinitely.
func TestSweepRemovesAbandoned(t *testing.T) {
	p, ctx := testPool(t)

	stale := abandoned(t, ctx, p, 2*time.Hour)
	fresh, err := p.Create(ctx)
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	t.Cleanup(func() { _ = fresh.Close() })

	// Nothing is old enough to sweep at this age, not even the stale one.
	if _, err := p.Sweep(ctx, 24*time.Hour); err != nil {
		t.Fatalf("Sweep: %v", err)
	}
	if !databaseExists(t, ctx, p, stale) {
		t.Fatal("a database younger than the age given was swept")
	}

	// At an age the abandoned one exceeds, it goes and the fresh one stays.
	if _, err := p.Sweep(ctx, time.Hour); err != nil {
		t.Fatalf("Sweep: %v", err)
	}
	if databaseExists(t, ctx, p, stale) {
		t.Error("an abandoned database survived a sweep that should have taken it")
	}
	if _, _, err := withOpenCheck(ctx, fresh); err != nil {
		t.Errorf("a shadow created moments ago was swept: %v", err)
	}
}

// TestSweepWillNotTakeSomethingJustCreated is the floor, and it is what keeps a
// sweep from being a hazard on a shared server.
//
// Create returns as soon as CREATE DATABASE succeeds; the caller connects
// afterwards. In that window the database has no connections, so a sweep that
// refuses only databases in use would drop it — which is how one test run took
// out another's shadow between its creation and its first query.
func TestSweepWillNotTakeSomethingJustCreated(t *testing.T) {
	p, ctx := testPool(t)

	db, err := p.Create(ctx)
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	t.Cleanup(func() { _ = db.Close() })

	// Nothing is connected to it yet, and zero means "everything is stale".
	if _, err := p.Sweep(ctx, 0); err != nil {
		t.Fatalf("Sweep: %v", err)
	}
	if !databaseExists(t, ctx, p, db.Name) {
		t.Error("a database created moments ago, with nothing yet connected to " +
			"it, was swept as abandoned")
	}
}

// withOpenCheck confirms a shadow database is still usable.
func withOpenCheck(ctx context.Context, db *DB) (*schema.Schema, schema.Version, error) {
	s, err := db.Schema(ctx)
	if err != nil {
		return nil, "", err
	}
	v, err := schema.Fingerprint(s)
	return s, v, err
}

// TestSweepLeavesLiveDatabasesAlone is the property that keeps a sweep from
// taking down everything else using the same server.
//
// Sweep identifies databases by name prefix, so on a shared host it sees every
// deployment's shadows and every concurrent test run's. It used to drop them
// WITH FORCE, which made "in use" no obstacle: a sweep with age zero terminated
// every open shadow connection on the host. Packages run in parallel under
// `go test ./...`, so this reliably and intermittently killed the diff and
// render suites, and would now also kill a proof the worker was in the middle
// of.
func TestSweepLeavesLiveDatabasesAlone(t *testing.T) {
	p, ctx := testPool(t)

	// Old enough to sweep, so that surviving proves the connection protected
	// it rather than the minimum age.
	name := abandoned(t, ctx, p, 2*time.Hour)
	dsn, err := withDatabase(p.adminDSN, name)
	if err != nil {
		t.Fatalf("dsn: %v", err)
	}

	// Hold a connection open, the way any run in progress would.
	conn, err := pgx.Connect(ctx, dsn)
	if err != nil {
		t.Fatalf("connect to the live shadow: %v", err)
	}
	defer conn.Close(context.Background())
	if err := conn.QueryRow(ctx, `SELECT 1`).Scan(new(int)); err != nil {
		t.Fatalf("the connection is not usable: %v", err)
	}

	// A sweep that considers this one stale must still not touch it.
	if _, err := p.Sweep(ctx, time.Hour); err != nil {
		t.Fatalf("Sweep: %v", err)
	}

	// The connection still works, and the database is still there.
	if err := conn.QueryRow(ctx, `SELECT 1`).Scan(new(int)); err != nil {
		t.Fatalf("a sweep killed a connection to a database in use: %v", err)
	}
	if !databaseExists(t, ctx, p, name) {
		t.Error("a sweep dropped a database that had an open connection")
	}
}

// abandoned creates a shadow database that looks as though it was left behind
// long ago, by writing an old timestamp into its name — which is exactly where
// Sweep reads an age from, there being no registry to consult.
//
// Tests sweep this rather than something freshly created, for the reason Sweep
// now enforces: on a shared server a sweep that considers everything stale
// considers every other package's shadows stale too, and packages run in
// parallel under `go test ./...`.
func abandoned(t *testing.T, ctx context.Context, p *Pool, age time.Duration) string {
	t.Helper()
	var b [6]byte
	if _, err := rand.Read(b[:]); err != nil {
		t.Fatalf("name: %v", err)
	}
	name := fmt.Sprintf("%s%d_%s", namePrefix,
		time.Now().Add(-age).UnixMilli(), hex.EncodeToString(b[:]))

	admin, err := pgx.Connect(ctx, p.adminDSN)
	if err != nil {
		t.Fatalf("connect to shadow host: %v", err)
	}
	defer admin.Close(context.Background())
	if _, err := admin.Exec(ctx, `CREATE DATABASE "`+name+`"`); err != nil {
		t.Fatalf("create the abandoned database: %v", err)
	}
	t.Cleanup(func() {
		bg := context.Background()
		a, err := pgx.Connect(bg, p.adminDSN)
		if err != nil {
			return
		}
		defer a.Close(bg)
		a.Exec(bg, `DROP DATABASE IF EXISTS "`+name+`" WITH (FORCE)`)
	})
	return name
}

func databaseExists(t *testing.T, ctx context.Context, p *Pool, name string) bool {
	t.Helper()
	admin, err := pgx.Connect(ctx, p.adminDSN)
	if err != nil {
		t.Fatalf("connect to shadow host: %v", err)
	}
	defer admin.Close(context.Background())
	var exists bool
	if err := admin.QueryRow(ctx,
		`SELECT EXISTS (SELECT 1 FROM pg_database WHERE datname = $1)`, name).
		Scan(&exists); err != nil {
		t.Fatalf("look for %s: %v", name, err)
	}
	return exists
}
