package store_test

import (
	"context"
	"errors"
	"os"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/rishabhju65/schemaver/internal/store"
)

// TestProposeReviewApprove walks the whole review flow against a live metadata
// database: propose bringing one database in line with another, generate the
// migration, and confirm the execute gate opens only once a project
// administrator has approved.
//
// It needs a deployment that already has a project with two observed databases,
// which is why it is gated on an explicit variable rather than run by default.
func TestProposeReviewApprove(t *testing.T) {
	url := os.Getenv("SCHEMAVER_METADATA_URL")
	if url == "" {
		t.Skip("set SCHEMAVER_METADATA_URL to run the review flow test")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	pool, err := pgxpool.New(ctx, url)
	if err != nil {
		t.Fatalf("connect: %v", err)
	}
	defer pool.Close()
	st := store.New(pool, nil)

	var projectID, userID, target, source int64
	if err := pool.QueryRow(ctx, `
		SELECT i.project_id,
		       (SELECT m.user_id FROM schemaver.project_member m
		         WHERE m.project_id = i.project_id AND m.role = 'admin' LIMIT 1),
		       (SELECT id FROM schemaver.database WHERE name = 'shop_prod'),
		       (SELECT id FROM schemaver.database WHERE name = 'shop_staging')
		  FROM schemaver.instance i LIMIT 1`).
		Scan(&projectID, &userID, &target, &source); err != nil {
		t.Fatalf("find fixtures: %v", err)
	}
	scope := st.ForProject(projectID)

	requestID, err := scope.Propose(ctx, userID, target, source,
		"bring production in line with staging", "generated by the review flow test")
	if err != nil {
		t.Fatalf("Propose: %v", err)
	}
	t.Logf("change request %d", requestID)

	migrationID, err := scope.GenerateMigration(ctx, requestID)
	if err != nil {
		t.Fatalf("GenerateMigration: %v", err)
	}
	t.Logf("migration %d", migrationID)

	var steps int
	var irreversible *string
	if err := pool.QueryRow(ctx, `
		SELECT (SELECT count(*) FROM schemaver.migration_step WHERE migration_id = $1),
		       (SELECT irreversible_reason FROM schemaver.migration WHERE id = $1)`,
		migrationID).Scan(&steps, &irreversible); err != nil {
		t.Fatalf("inspect migration: %v", err)
	}
	if steps == 0 {
		t.Fatal("no statements generated")
	}
	t.Logf("%d statements; irreversible: %v", steps, irreversible != nil)

	rows, _ := pool.Query(ctx,
		`SELECT ordinal, sql, transactional FROM schemaver.migration_step
		  WHERE migration_id = $1 ORDER BY ordinal`, migrationID)
	for rows.Next() {
		var n int
		var sql string
		var tx bool
		_ = rows.Scan(&n, &sql, &tx)
		mark := " "
		if !tx {
			mark = "!"
		}
		t.Logf("  %s %d. %s", mark, n, sql)
	}
	rows.Close()

	// Before approval the gate must be shut, and it must say why.
	state, err := scope.ApprovalState(ctx, requestID)
	if err != nil {
		t.Fatalf("ApprovalState: %v", err)
	}
	if state.Executable {
		t.Error("executable with no approval")
	}
	t.Logf("gate closed: %s", state.Reason)

	// A non-administrator cannot open it.
	var viewer int64
	err = pool.QueryRow(ctx, `
		SELECT user_id FROM schemaver.project_member
		 WHERE project_id = $1 AND role <> 'admin' LIMIT 1`, projectID).Scan(&viewer)
	if err == nil {
		if derr := scope.Decide(ctx, requestID, viewer, "approve", ""); !errors.Is(derr, store.ErrNotAdmin) {
			t.Errorf("a non-administrator approval was not refused: %v", derr)
		}
	}

	// The author is the project's only administrator here, so their own
	// approval is the only one obtainable and is recorded as self-approved.
	if err := scope.Decide(ctx, requestID, userID, "approve", "sole administrator"); err != nil {
		t.Fatalf("Decide: %v", err)
	}
	state, err = scope.ApprovalState(ctx, requestID)
	if err != nil {
		t.Fatalf("ApprovalState: %v", err)
	}
	if !state.Executable {
		t.Errorf("still not executable after an administrator approved: %s", state.Reason)
	}
	if len(state.Decisions) != 1 || !state.Decisions[0].SelfApproved {
		t.Errorf("self-approval not recorded: %+v", state.Decisions)
	}
	t.Logf("gate open; %d administrator approval(s), self-approved=%v",
		state.AdminApprovals, state.Decisions[0].SelfApproved)

	// Regenerating supersedes the migration, and the approval stops matching
	// without anything having to withdraw it.
	if _, err := scope.GenerateMigration(ctx, requestID); err != nil {
		t.Fatalf("regenerate: %v", err)
	}
	state, err = scope.ApprovalState(ctx, requestID)
	if err != nil {
		t.Fatalf("ApprovalState after regeneration: %v", err)
	}
	if state.Executable {
		t.Error("the approval survived regeneration; evidence must expire with the migration")
	}
	t.Logf("after regeneration the gate is shut again: %s", state.Reason)
}
