package store_test

import (
	"context"
	"errors"
	"os"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/rishabhju65/schemaver/internal/store"
)

// TestProposeReviewApprove walks the whole review flow against a live metadata
// database: propose bringing one database in line with another, generate the
// migration, and confirm the execute gate opens only once a project
// administrator has approved.
//
// It needs a deployment that already has a project with two observed databases,
// which is why it is gated on an explicit variable rather than run by default.
func TestProposeReviewApprove(t *testing.T) {
	url := os.Getenv("SCHEMAVER_METADATA_URL")
	if url == "" {
		t.Skip("set SCHEMAVER_METADATA_URL to run the review flow test")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	pool, err := pgxpool.New(ctx, url)
	if err != nil {
		t.Fatalf("connect: %v", err)
	}
	defer pool.Close()
	st := store.New(pool, nil)

	// Two databases of this test's own, at two schemas that genuinely differ.
	//
	// It used to diff the deployment's own shop_prod against shop_staging, and
	// so depended on them being out of line — which they are only until
	// something brings them together. Every successful migration, including the
	// ones this suite runs, consumed the very drift the next run needed, so it
	// passed once and then reported "the target database already matches the
	// source schema" until somebody re-introduced a difference by hand.
	//
	// No real PostgreSQL databases are involved: propose and generate work from
	// stored schemas, so two rows pointing at two blobs are a complete fixture.
	var projectID, userID, credentialID int64
	if err := pool.QueryRow(ctx, `
		SELECT m.project_id, m.user_id, i.credential_id
		  FROM schemaver.project_member m
		  JOIN schemaver.instance i ON i.project_id = m.project_id
		 WHERE m.role = 'admin' ORDER BY m.project_id LIMIT 1`).
		Scan(&projectID, &userID, &credentialID); err != nil {
		t.Skipf("no project with an administrator and a server: %v", err)
	}

	// Two schemas this project has actually observed. A blob is readable only
	// through a snapshot belonging to the caller — that is how D-014 keeps one
	// project from reading another's schemas — so an arbitrary pair of
	// fingerprints would be refused however real they are.
	var older, newer string
	if err := pool.QueryRow(ctx, `
		SELECT min(sn.fingerprint), max(sn.fingerprint)
		  FROM schemaver.snapshot sn
		  JOIN schemaver.database d ON d.id = sn.database_id
		  JOIN schemaver.instance i ON i.id = d.instance_id
		 WHERE i.project_id = $1 AND sn.fingerprint IS NOT NULL`, projectID).
		Scan(&older, &newer); err != nil || older == newer {
		t.Skipf("this project has not observed two different schemas: %v", err)
	}

	var instanceID int64
	if err := pool.QueryRow(ctx, `
		INSERT INTO schemaver.instance (project_id, name, host, credential_id)
		VALUES ($1, 'review-probe', 'probe.invalid', $2) RETURNING id`,
		projectID, credentialID).Scan(&instanceID); err != nil {
		t.Skipf("create the probe server: %v", err)
	}
	t.Cleanup(func() {
		bg := context.Background()
		// Change requests first. Deleting the databases while one still refers
		// to them fails on the foreign key, and because the error was discarded
		// the whole fixture survived — a fake server, visible in the fleet,
		// holding the host name the next run needs.
		pool.Exec(bg, `DELETE FROM schemaver.change_request
		                WHERE database_id IN (SELECT id FROM schemaver.database
		                                       WHERE instance_id = $1)`, instanceID)
		pool.Exec(bg, `DELETE FROM schemaver.database WHERE instance_id = $1`, instanceID)
		pool.Exec(bg, `DELETE FROM schemaver.instance WHERE id = $1`, instanceID)
	})

	var target, source int64
	for _, d := range []struct {
		name        string
		fingerprint string
		into        *int64
	}{
		{"probe_target", older, &target},
		{"probe_source", newer, &source},
	} {
		if err := pool.QueryRow(ctx, `
			INSERT INTO schemaver.database (instance_id, name, managed, current_fingerprint)
			VALUES ($1, $2, true, $3) RETURNING id`,
			instanceID, d.name, d.fingerprint).Scan(d.into); err != nil {
			t.Fatalf("create %s: %v", d.name, err)
		}
	}

	scope := st.ForProject(projectID)

	requestID, err := scope.Propose(ctx, userID, target, source,
		"bring production in line with staging", "generated by the review flow test")
	if err != nil {
		t.Fatalf("Propose: %v", err)
	}
	t.Logf("change request %d", requestID)

	migrationID, err := scope.GenerateMigration(ctx, userID, requestID)
	if err != nil {
		t.Fatalf("GenerateMigration: %v", err)
	}
	t.Logf("migration %d", migrationID)

	var steps int
	var irreversible *string
	if err := pool.QueryRow(ctx, `
		SELECT (SELECT count(*) FROM schemaver.migration_step WHERE migration_id = $1),
		       (SELECT irreversible_reason FROM schemaver.migration WHERE id = $1)`,
		migrationID).Scan(&steps, &irreversible); err != nil {
		t.Fatalf("inspect migration: %v", err)
	}
	if steps == 0 {
		t.Fatal("no statements generated")
	}
	t.Logf("%d statements; irreversible: %v", steps, irreversible != nil)

	rows, _ := pool.Query(ctx,
		`SELECT ordinal, sql, transactional FROM schemaver.migration_step
		  WHERE migration_id = $1 ORDER BY ordinal`, migrationID)
	for rows.Next() {
		var n int
		var sql string
		var tx bool
		_ = rows.Scan(&n, &sql, &tx)
		mark := " "
		if !tx {
			mark = "!"
		}
		t.Logf("  %s %d. %s", mark, n, sql)
	}
	rows.Close()

	// A freshly generated migration is shut on its proof before anybody has
	// even looked at it: approving something that has not been shown to produce
	// the schema it claims would be approving a guess.
	// A freshly generated migration has no way back, because nothing generates
	// one: whoever wrote the change writes the revert (D-022). The gate says so
	// before it says anything about proofs, since this is the author's to fix
	// and a proof cannot run on a plan that is not finished.
	state, err := scope.ApprovalState(ctx, requestID)
	if err != nil {
		t.Fatalf("ApprovalState: %v", err)
	}
	if state.Executable {
		t.Error("executable with no way back written")
	}
	if state.RevertWritten {
		t.Error("a generated migration arrived with a revert; nothing should generate one")
	}
	t.Logf("gate closed on the missing revert: %s", state.Reason)

	if err := scope.WriteRevert(ctx, userID, migrationID,
		"ALTER TABLE public.orders DROP COLUMN channel;"); err != nil {
		t.Fatalf("WriteRevert: %v", err)
	}

	// Stand in for the worker, which is not running here. Both halves: the gate
	// wants the migration rehearsed and the way back shown to lead back.
	if err := st.RecordProof(ctx, migrationID, "passed", "", nil); err != nil {
		t.Fatalf("RecordProof: %v", err)
	}
	if err := st.RecordRevertProof(ctx, migrationID, "passed", ""); err != nil {
		t.Fatalf("RecordRevertProof: %v", err)
	}

	// Before approval the gate must still be shut, and it must say why.
	state, err = scope.ApprovalState(ctx, requestID)
	if err != nil {
		t.Fatalf("ApprovalState: %v", err)
	}
	if state.Executable {
		t.Error("executable with no approval")
	}
	t.Logf("gate closed: %s", state.Reason)

	// A non-administrator cannot open it.
	var viewer int64
	err = pool.QueryRow(ctx, `
		SELECT user_id FROM schemaver.project_member
		 WHERE project_id = $1 AND role <> 'admin' LIMIT 1`, projectID).Scan(&viewer)
	if err == nil {
		if derr := scope.Decide(ctx, requestID, viewer, "approve", ""); !errors.Is(derr, store.ErrNotAdmin) {
			t.Errorf("a non-administrator approval was not refused: %v", derr)
		}
	}

	// The author is the project's only administrator here, so their own
	// approval is the only one obtainable and is recorded as self-approved.
	if err := scope.Decide(ctx, requestID, userID, "approve", "sole administrator"); err != nil {
		t.Fatalf("Decide: %v", err)
	}
	state, err = scope.ApprovalState(ctx, requestID)
	if err != nil {
		t.Fatalf("ApprovalState: %v", err)
	}
	if !state.Executable {
		t.Errorf("still not executable after an administrator approved: %s", state.Reason)
	}
	if len(state.Decisions) != 1 || !state.Decisions[0].SelfApproved {
		t.Errorf("self-approval not recorded: %+v", state.Decisions)
	}
	t.Logf("gate open; %d administrator approval(s), self-approved=%v",
		state.AdminApprovals, state.Decisions[0].SelfApproved)

	// Regenerating supersedes the migration, and both the approval and the proof
	// stop applying without anything having to withdraw them. Both are evidence
	// about one fingerprint pair, and the new migration is a different row.
	if _, err := scope.GenerateMigration(ctx, userID, requestID); err != nil {
		t.Fatalf("regenerate: %v", err)
	}
	state, err = scope.ApprovalState(ctx, requestID)
	if err != nil {
		t.Fatalf("ApprovalState after regeneration: %v", err)
	}
	if state.Executable {
		t.Error("the approval survived regeneration; evidence must expire with the migration")
	}
	if state.RevertWritten {
		t.Error("the regenerated migration kept the previous revert; a way back " +
			"written for other statements is not a way back from these")
	}
	t.Logf("after regeneration the gate is shut again: %s", state.Reason)
}
